<script setup lang="ts">
import { computed, defineAsyncComponent, type Component } from 'vue';
import { webkitComponentLoaders, webkitRegistry } from '../../generated/playground-registry';

/**
 * WebkitPreview
 *
 * Dynamically loads and renders a component from @aziontech/webkit based on
 * its documentation slug. Used by auto-scaffolded component pages to provide
 * a live preview without requiring manually authored demo wrappers.
 *
 * The componentSlug maps to an entry in playground-registry.ts which was
 * generated by scripts/scaffoldComponentDocs.ts. Each loader uses a static
 * import expression so Vite can statically analyze all import paths.
 *
 * Usage (in scaffolded .mdx):
 *   <WebkitPreview componentSlug="form-field-text" client:load />
 */

interface Props {
  /** Slug matching an entry in playground-registry.ts (e.g. 'form-field-text') */
  componentSlug: string;
  /**
   * Optional props to forward to the rendered component.
   * Useful for required props like `name` on form fields.
   */
  componentProps?: Record<string, unknown>;
}

const props = withDefaults(defineProps<Props>(), {
  componentProps: () => ({}),
});

const registryEntry = computed(() =>
  webkitRegistry.find((e) => e.slug === props.componentSlug),
);

const resolvedComponent = computed<Component | null>(() => {
  const loader = webkitComponentLoaders[props.componentSlug];
  if (!loader) return null;
  return defineAsyncComponent({
    loader,
    errorComponent: {
      template: `<div class="text-sm text-red-500 py-2">Failed to load component.</div>`,
    },
    loadingComponent: {
      template: `<div class="text-sm text-muted py-2 animate-pulse">Loading preview…</div>`,
    },
    delay: 100,
    timeout: 8000,
  });
});

/**
 * Default preview props: form fields need at least a `name` attribute for
 * vee-validate's useField to work without errors. Additional required props
 * passed via componentProps will override these defaults.
 */
const defaultPreviewProps = computed(() => ({
  name: `preview-${props.componentSlug}`,
  ...props.componentProps,
}));
</script>

<template>
  <div class="webkit-preview not-prose my-6">
    <!-- Registry not found -->
    <div
      v-if="!registryEntry"
      class="flex items-center gap-2 rounded-lg border border-dashed border-default bg-surface px-4 py-6 text-sm text-muted"
    >
      <i class="pi pi-exclamation-circle" aria-hidden="true" />
      Component <code class="mx-1 rounded bg-gray-100 px-1 text-xs">{{ componentSlug }}</code> not found in playground registry.
    </div>

    <!-- Live preview -->
    <div
      v-else
      class="rounded-lg border border-default bg-white p-8 dark:border-gray-700 dark:bg-surface-900"
    >
      <div class="mb-3 flex items-center gap-2">
        <span class="rounded-full bg-blue-50 px-2 py-0.5 text-xs font-medium text-blue-600 dark:bg-blue-900/30 dark:text-blue-400">
          {{ registryEntry.displayName }}
        </span>
        <span class="text-xs text-muted">Live preview</span>
      </div>

      <Suspense>
        <component
          :is="resolvedComponent"
          v-bind="defaultPreviewProps"
        />
        <template #fallback>
          <div class="animate-pulse text-sm text-muted">Loading component…</div>
        </template>
      </Suspense>
    </div>
  </div>
</template>
