name: Storybook Publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Storybook
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine3.18
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: CHECKOUT project
        uses: actions/checkout@v4
        with:
          repository: aziontech/azion-webkit
          ref: main
          path: '.'
          clean: true
          fetch-depth: '0'
          lfs: 'false'
      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Installing dependencies
        run: npm install
      - name: Building azion-webkit
        run: npm run build:package
      - name: Building Storybook
        run: npm run build:storybook
      - name: PREPARING TO DEPLOY
        run: rm -rf .github .storybook dist doc node_modules src .editorconfig .eslintrc.cjs .gitignore .prettierrc.json .releaserc build-package.js CHANGELOG.md CLA.md CODE_OF_CONDUCT.md CODEOWNERS CONTRIBUTING.md index.html LICENSE package-lock.json package.json postcss.config.js README.md tailwind.config.cjs tsconfig.json vite.config.js vitest.config.js; mv storybook-static/* .; rm -rf storybook-static;
      - name: Deployng Storybook
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.GCP_BUCKET_KEY }}
          bucket: ${{ secrets.GCP_BUCKET_NAME }}
